### PR TITLE
Update resources

### PR DESCRIPTION
**Pull request by ryanwalder**
Automatically updated using the makecode.py script.

Needed to do this for some new AWS resources for myself, though I'd make a PR.

### CODE REVIEW

**Comment by nielsonsantana** [comment]
Hi @ryanwalder. Great!! 
Did you commited the `makescript.py`?

**Comment by ryanwalder** [comment]
@nielsonsantana I just used `makecode.py` in the root of the repo, looks like it reads from `PROVIDERS` then grabs things from github and outputs the code. I'm assuming this works?

**Comment by nielsonsantana** [comment]
@ryanwalder, You are right! I didn't saw this file. I was building a script to automate it and I didn't realize that there a `makescript.py` to update resources.

**Comment by mjuenema** [comment]
Thanks, everyone.

**Pull request merged**
