### PR TITLE
Should try to determine the provider.go location in directory

### PR DESCRIPTION
**Pull request by ilons**
## Changed
* Script to generate providers would now try to guess the location of the required provider.go in the repository

### CODE REVIEW

**Comment by ilons** [comment]
Here is an opportunistic approach to finding the providers.go location, which will at least avoid spitting out error for the providers currently listed (but might not generate anything meaningful for them).

**Review by mjuenema — APPROVED** [review]
Have a look at the latest entries in discussion #149. Maybe a complete rewrite of ``makecode.py`` to generate the code from ``terraform providers schema -json`` is the better long-term option.

I approved your Pull Request regardless.

**Comment by ilons** [comment]
@mjuenema Yes, I read it, and that would indeed be a much better solution. Meanwhile, I think it make sense to make those changes, since a rewrite wont happen overnight (for me at least :-) ).

Also, sorry about pushing more changes on the same branch after I assigned you, I'll be done for the night now tho!

**Comment by mjuenema** [comment]
No problem, I agree with that approach. 

My day has just started...

**Pull request merged**
