### PR TITLE
Added new cloudflare resources and data

### PR DESCRIPTION
**Pull request by byjg**
I added the new cloudflare resources and data.

### CODE REVIEW

**Comment by byjg** [comment]
Just to know -- The fail in the travis is not because my PR.

**Comment by nielsonsantana** [comment]
I fixed the issue (https://travis-ci.org/mjuenema/python-terrascript/builds/426822364). After my PR be merged, you would merge with master and update your PR.

**Comment by byjg** [comment]
Any idea when this PR will be merged??

**Comment by mjuenema** [comment]
Sorry, I am flat out at work and have little time for other projects at the moment. I'll try to merge this PR and also create a new release as soon as as possible. You are not forgotten...

**Pull request merged**
