### PR TITLE
Should include more explicit request for contributions

### PR DESCRIPTION
**Pull request by ilons**
### Changed
* Wording about looking for new maintainer now instead asks for contributions, and CONTRIBUTORS.md are slightly updated

### CODE REVIEW

**Review by mjuenema — APPROVED** [review]
Hi am happy with the change. At some stage the wording "in no particular order" should be changed to "in alphabetical order" as it is obviously in that order.

**Comment by ilons** [comment]
> Hi am happy with the change. At some stage the wording "in no particular order" should be changed to "in alphabetical order" as it is obviously in that order.

I agree, but intentionally left it there, as a safeguard for the ones we have missed, and when it becomes unsorted :)

**Comment by ilons** [comment]
Not really related to this PR but.. Would you mind turning on automatic deletion of stale branches in the settings for the repository?

**Comment by mjuenema** [comment]
Is that the "Automatically delete head branches" under Options?

**Comment by ilons** [comment]
> Is that the "Automatically delete head branches" under Options?

Indeed it is.

**Comment by mjuenema** [comment]
Done

**Pull request merged**
