### PR TITLE
Add terraform settings block and data block, fix depends_on attributes

### PR DESCRIPTION
**Pull request by MaT1g3R**
- Add the class `Terraform` to represent terraform settings
- Add the class `Data` to represent terraform data
- https://www.terraform.io/docs/configuration/syntax-json.html#terraform-blocks
- Add depends_on string conversion for the Block base class so depends_on will dump properly

### CODE REVIEW

**Comment by mjuenema** [comment]
That's a lot :-) I need to find time to have a closer look at all this. Sorry for the delay.

**Comment by mjuenema** [comment]
Have you tested this against Terraform 0.12 ? The current automated tests don't cover Terraform 0.12.

I started the feature/terraform_0.12 branch specifically for Terraform 0.12 with the intention to rewrite a lot of code. There is probably a lot of really good stuff in your pull request but I may have to work out how everything will fit together.

**Comment by MaT1g3R** [comment]
Sorry for the big PR, we are in the middle of moving to terrascript so I took my liberties and implemented features as I went along.

We just rebuilt our test environment with terraform 0.12.6 and terrascript today , and it worked fine

**Comment by mjuenema** [comment]
No problem at all. It's actually really nice (and a bit scary) to realise that other people find my little project useful. I am going to merge your pull request this evening (Melbourne time). 

I might also temporarily create a separate branch just for your pull requests as I wanted to continue making (potentially major) changes to a (renamed) terraform_0.12 branch. I'll keep you updated.

**Comment by MaT1g3R** [comment]
Do you have any specific plans for Terraform 0.12 (although that is working now) and a 0.7 release? We would love to send more PRs to help out.

**Comment by mjuenema** [comment]
Let me get back to you later today, I am currently at work...

**Comment by mjuenema** [comment]
Hi, there are now separate Git ``develop-0.x`` branches for Terrascript 0.6.x (Terraform 0.11.x) and Terrascript 0.7.x. (Terraform 0.12). Please submit any future Pull Request to one of those branches. There is some more information about this in the ``README.md`` file of the ``develop`` branch.

**Pull request merged**
