### PR TITLE
Updated Travis build and Codecov to reflect master branch

### PR DESCRIPTION
**Pull request by nielsonsantana**
This PR is for update the Travis build and Codecov to reflect the master branch.

### CODE REVIEW

**Comment by mjuenema** [comment]
Hi Nielson. I just removed the whole Codecov stuff because its Python requirements caused problems. Codecov processing is not essential and I really don't want to trouble-shoot problems that are not part of Terrascript's core functionality.

**Comment by nielsonsantana** [comment]
Ok @mjuenema. I will update the branch with your changes.

**Comment by mjuenema** [comment]
I am not very familiar with the Shields site. What is the advantage of referencing the master branch directly in the link?

**Comment by mjuenema** [comment]
> Ok @mjuenema. I will update the branch with your changes.

I might simply copy-and-paste your changes as I am in the very process of releasing 0.6.0.

**Comment by mjuenema** [comment]
Good morning to Brasil, by the way. I am about to go to bed here in Melbourne, Australia ;-)

**Comment by nielsonsantana** [comment]
Almost all projects that I saw using flags, use the branch master as source. It's show if the master branch is stable and can be used to work.

**Comment by nielsonsantana** [comment]
Thanks!! Good Night!!

**Comment by nielsonsantana** [comment]
> > Ok @mjuenema. I will update the branch with your changes.
> 
> I might simply copy-and-paste your changes as I am in the very process of releasing 0.6.0.

Great!!

**Comment by mjuenema** [comment]
"Merged" by copy-and-paste as it was easier at the time. Thanks!

**Pull request closed without merging**
