### PR TITLE
Added support for update terrascript from another terrascript. Same behavior as dict().update

### PR DESCRIPTION
**Pull request by nielsonsantana**
While using `Terrascript`, I missed one way to join/merge two existing terrascripts. This possibility is indispensable for modularity, once we can divide a whole infrastructure into smaller parts and reuse it. 
In this pull request I implemented a new method called (`update`) on `Terrascript`.

The behavior of this method is similar as implemented in [`dict.update`](https://docs.python.org/2/library/stdtypes.html#dict.update). 
In this case, the method `update`, does two operations:

* Override a previous item declared in Terrascript;
* Add a new item not declared yet in Terrascript;

**Example 1: Override a previous declared item in `ts`:**

```python
    ts = Terrascript()
    ts2 = Terrascript()

    var_region = ts.add(variable('region', default='us-east-1'))
    var_region2 = ts2.add(variable('region', default='ca-central-1'))
    print('before:\n', ts.dump)
    ts.update(ts2)
    print('after:\n', ts.dump)
```
Result:
```json
   before:
   {
      "variable": {
        "region": {
          "default": "us-east-1"
        }
      }
    }
```
```json
   After:
   {
      "variable": {
        "region": {
          "default": "ca-central-1"
        }
      }
    }
```

**Example 2: add a new item not declared in `ts`:**

```python
    ts = Terrascript()
    ts2 = Terrascript()

    var_region2 = ts2.add(variable('region', default='ca-central-1'))
    print('before:\n', ts.dump)
    ts.update(ts2)
    print('after:\n', ts.dump)
```
Result:
```json
   before:
   { }
```
```json
   After:
   {
      "variable": {
        "region": {
          "default": "ca-central-1"
        }
      }
    }
```

### CODE REVIEW

**Comment by nielsonsantana** [comment]
@mjuenema, as related in #38, was introduced a build error after add versions of Terraform.

**Comment by nielsonsantana** [comment]
@mjuenema, should I send this pull request against branch [issue33](https://github.com/mjuenema/python-terrascript/tree/issue33)?

**Comment by mjuenema** [comment]
Thanks, this will go into 0.5.2 earliest. I want to get 0.5.1 out quickly as it contains important fixes.

**Comment by nielsonsantana** [comment]
Hi @mjuenema. I'm back working on terrascript. I resolved the conflict, but I think that the test suit has some problem on python-3.3. 
The first issue was https://travis-ci.org/mjuenema/python-terrascript/jobs/426097817 . 
I tried solve by add the 'setuptools>=18.5' to test_requirments.txt, but another error happen.
https://travis-ci.org/mjuenema/python-terrascript/jobs/426102810 .
How solve this issue? Drop test for python-3.3?

I did the same test using a docker image python-3.3.6 and I can't reproduce the second error presented by travis-ci.

**Comment by mjuenema** [comment]
The Travis-CI output shows that the problem seems to be installing the ``codecov``` and ```github3``` modules. From memory, they are only needed for the Codecov feature which I can live without.

**Comment by nielsonsantana** [comment]
Hi @mjuenema. I solved the bug with dependencies. Build timeline: https://travis-ci.org/mjuenema/python-terrascript/builds/426822364. The unique issue was because a timeout: https://travis-ci.org/mjuenema/python-terrascript/jobs/426822429.

**Pull request merged**
